# Generated by Django 3.0.7 on 2020-06-25 07:55

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50, verbose_name='Cidade')),
                ('state', models.CharField(max_length=2, verbose_name='UF')),
            ],
            options={
                'verbose_name': 'Localização',
                'verbose_name_plural': 'Localizações',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Título do projeto')),
                ('image', models.ImageField(upload_to=core.models.upload_image_path, verbose_name='Foto do projeto')),
                ('description', models.TextField(max_length=1000, verbose_name='Descrição do projeto')),
                ('link', models.CharField(blank=True, max_length=250, null=True, verbose_name='Link para o projeto')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em ')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em ')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nome Completo')),
                ('email', models.EmailField(max_length=100, verbose_name='E-mail')),
                ('phone', models.CharField(max_length=15, verbose_name='Telefone')),
                ('image', models.ImageField(upload_to=core.models.upload_image_path, verbose_name='Foto de perfil')),
                ('title', models.CharField(max_length=50, verbose_name='Título do perfil')),
                ('sub_title', models.CharField(max_length=150, verbose_name='Subtítulo do perfil')),
                ('description', models.TextField(max_length=1000, verbose_name='Descrição do projeto')),
                ('country', models.CharField(max_length=20, verbose_name='País')),
                ('site_url', models.CharField(max_length=100, verbose_name='URL do site')),
                ('facebook_url', models.CharField(max_length=100, verbose_name='URL do facebook')),
                ('linkedin_url', models.CharField(max_length=100, verbose_name='URL do linkedin')),
                ('instagram_url', models.CharField(max_length=100, verbose_name='URL do instagram')),
                ('github_url', models.CharField(max_length=100, verbose_name='URL do github')),
                ('gitlab_url', models.CharField(max_length=100, verbose_name='URL do gitlab')),
                ('locality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Locality', verbose_name='Localização')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfil',
            },
        ),
    ]
